#!/bin/sh

if [ -n "$2" ]; then
    token=`echo -n $1 | md5sum | awk '{print $1}'`
    shift 1
    curl -b "Auth=${token}" http://127.0.0.1:8000"$@"
else
    echo "Usage: $0 USERNAME PATH [curl OPTIONS]"
fi
