#!/bin/sh

if [ -n "$1" ]; then
    token=`echo -n $1 | md5sum | awk '{print $1}'`
    curl -X POST http://127.0.0.1:8000/auth -d "{\"token\":\"${token}\", \"user\":\"$1\"}"
    echo "Login $1"
else
    echo "Usage: $0 USERNAME"
fi
